version: '2.0'

x-shared:
  &common
  NEO4J_dbms_mode: SINGLE
  NEO4J_AUTH: neo4j/password
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_memory_pagecache_size: "100M"
  NEO4J_dbms_memory_heap_initial__size: "100M"
  NEO4JLABS_PLUGINS: '["apoc"]'

networks:
  lan:
    driver: bridge

services:

  canada:
    image: neo4j:4.3-enterprise
    networks:
      - lan 
    ports: 
      - "17474:17474"
      - "17687:17687"
    volumes:
      - "./dbcanada/conf:/conf"
      - "./dbcanada/data:/data"
      - "./dbcanada/logs:/logs"
      - "./dbcanada/metrics:/metrics"
      - "./dbcanada/plugins:/plugins"
    environment:
      <<: *common
      NEO4J_dbms_connector_http_listen__address: ":17474"
      NEO4J_dbms_connector_bolt_listen__address: ":17687"
      NEO4J_dbms_connector_bolt_advertised__address: canada:17687
      NEO4J_dbms_default__database: dbcanada
