version: '3.8'

x-shared:
  &common
  NEO4J_dbms_mode: SINGLE
  NEO4J_AUTH: neo4j/password
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_memory_pagecache_size: "100M"
  NEO4J_dbms_memory_heap_initial__size: "100M"
  NEO4JLABS_PLUGINS: '["apoc"]'

networks:
  lan:
    driver: bridge

services:

  europe:
    image: neo4j:4.3-enterprise
    networks:
      - lan 
    ports: 
      - "17474:17474"
      - "17687:17687"
    volumes:
      - "./dbeurope/conf:/conf"
      - "./dbeurope/data:/data"
      - "./dbeurope/logs:/logs"
      - "./dbeurope/metrics:/metrics"
      - "./dbeurope/plugins:/plugins"
    environment:
      <<: *common
      NEO4J_dbms_connector_http_listen__address: ":17474"
      NEO4J_dbms_connector_bolt_listen__address: ":17687"
      NEO4J_dbms_connector_bolt_advertised__address: europe:17687
      NEO4J_dbms_default__database: dbeurope


  northamerica:
    image: neo4j:4.3-enterprise
    networks:
      - lan
    ports:
      - "17475:17475"
      - "17688:17688"
    volumes:
      - "./dbnorthamerica/conf:/conf"
      - "./dbnorthamerica/data:/data"
      - "./dbnorthamerica/logs:/logs"
      - "./dbnorthamerica/metrics:/metrics"
      - "./dbnorthamerica/plugins:/plugins"
    environment:
      <<:  *common
      NEO4J_dbms_connector_http_listen__address: ":17475"
      NEO4J_dbms_connector_bolt_listen__address: ":17688"
      NEO4J_dbms_connector_bolt_advertised__address: northamerica:17688
      NEO4J_dbms_default__database: dbnorthamerica

  southamerica:
    image: neo4j:4.3-enterprise
    networks:
      - lan
    ports:
      - "17476:17476"
      - "17689:17689"
    volumes:
      - "./dbsouthamerica/conf:/conf"
      - "./dbsouthamerica/data:/data"
      - "./dbsouthamerica/logs:/logs"
      - "./dbsouthamerica/metrics:/metrics"
      - "./dbsouthamerica/plugins:/plugins"
    environment:
      <<:  *common
      NEO4J_dbms_connector_http_listen__address: ":17476"
      NEO4J_dbms_connector_bolt_listen__address: ":17689"
      NEO4J_dbms_connector_bolt_advertised__address: southamerica:17689
      NEO4J_dbms_default__database: dbsouthamerica

  fabric:
    image: neo4j:4.3-enterprise
    networks:
      - lan
    ports:
      - "17477:17477"
      - "17690:17690"
    environment:
      <<:  *common

      NEO4J_dbms_connector_http_listen__address: ":17477"
      NEO4J_dbms_connector_bolt_listen__address: ":17690"
      NEO4J_dbms_connector_bolt_advertised__address: fabric:17690

      NEO4J_fabric_database_name: fabricnw
      
      NEO4J_fabric_routing_servers: europe:17687,northamerica:17688,southamerica:17689
      
      NEO4J_fabric_graph_0_name: "europe"
      NEO4J_fabric_graph_0_uri: neo4j://europe:17687
      NEO4J_fabric_graph_0_database: dbeurope

      NEO4J_fabric_graph_1_name: "northamerica"
      NEO4J_fabric_graph_1_uri: neo4j://northamerica:17688
      NEO4J_fabric_graph_1_database: dbnorthamerica
      
      NEO4J_fabric_graph_2_name: "southamerica"
      NEO4J_fabric_graph_2_uri: neo4j://southamerica:17689
      NEO4J_fabric_graph_2_database: dbsouthamerica
      