version: '2.0'

x-shared:
  &common
  NEO4J_dbms_mode: SINGLE
  NEO4J_AUTH: neo4j/password
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_memory_pagecache_size: "100M"
  NEO4J_dbms_memory_heap_initial__size: "100M"
  NEO4JLABS_PLUGINS: '["apoc"]'

networks:
  lan:
    driver: bridge

services:

  usa:
    image: neo4j:4.3-enterprise
    networks:
      - lan
    ports:
      - "17476:17476"
      - "17689:17689"
    volumes:
      - "./dbusa/conf:/conf"
      - "./dbusa/data:/data"
      - "./dbusa/logs:/logs"
      - "./dbusa/metrics:/metrics"
      - "./dbusa/plugins:/plugins"
    environment:
      <<:  *common
      NEO4J_dbms_connector_http_listen__address: ":17476"
      NEO4J_dbms_connector_bolt_listen__address: ":17689"
      NEO4J_dbms_connector_bolt_advertised__address: 0.0.0.0:17689
      NEO4J_dbms_default__database: dbusa
