version: '2.0'

x-shared:
  &common
  NEO4J_dbms_mode: SINGLE
  NEO4J_AUTH: neo4j/password
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_memory_pagecache_size: "100M"
  NEO4J_dbms_memory_heap_initial__size: "100M"
  NEO4JLABS_PLUGINS: '["apoc"]'

networks:
  lan:
    driver: bridge

services:

  mexico:
    image: neo4j:4.3-enterprise
    networks:
      - lan
    ports:
      - "17475:17475"
      - "17688:17688"
    volumes:
      - "./dbmexico/conf:/conf"
      - "./dbmexico/data:/data"
      - "./dbmexico/logs:/logs"
      - "./dbmexico/metrics:/metrics"
      - "./dbmexico/plugins:/plugins"
    environment:
      <<:  *common
      NEO4J_dbms_connector_http_listen__address: ":17475"
      NEO4J_dbms_connector_bolt_listen__address: ":17688"
      NEO4J_dbms_connector_bolt_advertised__address: 0.0.0.0:17688
      NEO4J_dbms_default__database: dbmexico

  administrator:
    image: neo4j:4.3-enterprise
    networks:
      - lan
    ports:
      - "17477:17477"
      - "17690:17690"
    environment:
      <<:  *common

      NEO4J_dbms_connector_http_listen__address: ":17477"
      NEO4J_dbms_connector_bolt_listen__address: ":17690"
      NEO4J_dbms_connector_bolt_advertised__address: 0.0.0.0:17690

      NEO4J_fabric_database_name: administrator
      
      NEO4J_fabric_routing_servers: 25.7.37.171:17687,25.7.138.176:17688,25.7.25.240:17689
      
      NEO4J_fabric_graph_0_name: "canada"
      NEO4J_fabric_graph_0_uri: neo4j://25.7.37.171:17687
      NEO4J_fabric_graph_0_database: dbcanada

      NEO4J_fabric_graph_1_name: "mexico"
      NEO4J_fabric_graph_1_uri: neo4j://25.7.138.176:17688
      NEO4J_fabric_graph_1_database: dbmexico
      
      NEO4J_fabric_graph_2_name: "usa"
      NEO4J_fabric_graph_2_uri: neo4j://25.7.25.240:17689
      NEO4J_fabric_graph_2_database: dbusa
      
