version: '2.0'

x-shared:
  &common
  NEO4J_dbms_mode: SINGLE
  NEO4J_AUTH: neo4j/password
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
  NEO4J_dbms_memory_pagecache_size: "100M"
  NEO4J_dbms_memory_heap_initial__size: "100M"
  NEO4JLABS_PLUGINS: '["apoc"]'

networks:
  lan:
    driver: bridge

services:

#  server:
#    image: node:14.15.0
#    depends_on:
#      - canada
#      - mexico
#      - usa
#      - administrator
#    networks:
#      - lan
#    ports:
#      - "8100:8100"
#    volumes:
#      - "./server:/app"
#    working_dir: /app
#    command: sh -c "sleep 2m && node_modules/.bin/tsc && node dist/main.js"

  canada:
    image: neo4j:4.3-enterprise
    networks:
      - lan 
    ports: 
      - "17474:17474"
      - "17687:17687"
    volumes:
      - "./dbcanada/conf:/conf"
      - "./dbcanada/data:/data"
      - "./dbcanada/logs:/logs"
      - "./dbcanada/metrics:/metrics"
      - "./dbcanada/plugins:/plugins"
    environment:
      <<: *common
      NEO4J_dbms_connector_http_listen__address: ":17474"
      NEO4J_dbms_connector_bolt_listen__address: ":17687"
      NEO4J_dbms_connector_bolt_advertised__address: canada:17687
      NEO4J_dbms_default__database: dbcanada


  mexico:
    image: neo4j:4.3-enterprise
    networks:
      - lan
    ports:
      - "17475:17475"
      - "17688:17688"
    volumes:
      - "./dbmexico/conf:/conf"
      - "./dbmexico/data:/data"
      - "./dbmexico/logs:/logs"
      - "./dbmexico/metrics:/metrics"
      - "./dbmexico/plugins:/plugins"
    environment:
      <<:  *common
      NEO4J_dbms_connector_http_listen__address: ":17475"
      NEO4J_dbms_connector_bolt_listen__address: ":17688"
      NEO4J_dbms_connector_bolt_advertised__address: mexico:17688
      NEO4J_dbms_default__database: dbmexico

  usa:
    image: neo4j:4.3-enterprise
    networks:
      - lan
    ports:
      - "17476:17476"
      - "17689:17689"
    volumes:
      - "./dbusa/conf:/conf"
      - "./dbusa/data:/data"
      - "./dbusa/logs:/logs"
      - "./dbusa/metrics:/metrics"
      - "./dbusa/plugins:/plugins"
    environment:
      <<:  *common
      NEO4J_dbms_connector_http_listen__address: ":17476"
      NEO4J_dbms_connector_bolt_listen__address: ":17689"
      NEO4J_dbms_connector_bolt_advertised__address: usa:17689
      NEO4J_dbms_default__database: dbusa

  administrator:
    image: neo4j:4.3-enterprise
    networks:
      - lan
    ports:
      - "17477:17477"
      - "17690:17690"
    environment:
      <<:  *common

      NEO4J_dbms_connector_http_listen__address: ":17477"
      NEO4J_dbms_connector_bolt_listen__address: ":17690"
      NEO4J_dbms_connector_bolt_advertised__address: administrator:17690

      NEO4J_fabric_database_name: administrator
      
      NEO4J_fabric_routing_servers: canada:17687,mexico:17688,usa:17689
      
      NEO4J_fabric_graph_0_name: "canada"
      NEO4J_fabric_graph_0_uri: neo4j://canada:17687
      NEO4J_fabric_graph_0_database: dbcanada

      NEO4J_fabric_graph_1_name: "mexico"
      NEO4J_fabric_graph_1_uri: neo4j://mexico:17688
      NEO4J_fabric_graph_1_database: dbmexico
      
      NEO4J_fabric_graph_2_name: "usa"
      NEO4J_fabric_graph_2_uri: neo4j://usa:17689
      NEO4J_fabric_graph_2_database: dbusa
      
